### ISSUE TITLE
xdebug enable: cannot unmarshal !!str `enable` into bool

### ISSUE THREAD

**Issue by moroland** [ironstar-io/tokaido#100]
**What happened**:

$ tok config-set tokaido xdebug enable
2019/01/11 13:59:46 There was an issue updating your config file
yaml: unmarshal errors:
  line 2: cannot unmarshal !!str `enable` into bool

**Comment by moroland** [comment]
`tok config-set tokaido xdebug true` works

**Comment by Benjen** [comment]
I encountered the same issue. I was also able to resolve it by setting the xdebug parameter as `true` instead of `enable`.

**Comment by otakumike** [comment]
Thanks guys. I've fixed the offending documentation
