### ISSUE TITLE
`tok open` doesn't using port 5154 without running `tok rebuild` first 

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#105]
**What happened**:
Ran `tok up`. Browser opened `https://localhost:32777/` and complains about untrusted SSL certificate.

**What you expected to happen**:
Expected the browser to open `https://mysite.local.tokaido.io:5154`.

**How to reproduce it (as minimally and precisely as possible)**:
* Run `tok up -d`
* Run `tok open`

**Anything else we need to know?**:
I am able to fix the problem by running `tok rebuild` after `tok up -d`. After `tok rebuild` has completed, `tok open` works as expected.

**Environment**:
- Tokaido version (use `tok version`): 1.5.0
- Drupal version: 7
- Operating system and version: OSX 10.12.6

**Additional context**
n/a

**Comment by Benjen** [comment]
He is output of `tok ps` after `tok open` fails to work correctly:

unsw_adminer_1    entrypoint.sh docker-php-e ...   Up      0.0.0.0:32769->8080/tcp
unsw_drush_1      /usr/local/bin/entrypoint.sh     Up      0.0.0.0:32773->22/tcp
unsw_fpm_1        /usr/local/bin/entrypoint.sh     Up      0.0.0.0:32779->9000/tcp
unsw_haproxy_1    /usr/local/bin/entrypoint.sh     Up      0.0.0.0:32778->8080/tcp, 0.0.0.0:32777->8443/tcp
unsw_kishu_1      /usr/local/bin/entrypoint.sh     Up
unsw_mailhog_1    MailHog                          Up      0.0.0.0:32771->1025/tcp, 0.0.0.0:32770->8025/tcp
unsw_memcache_1   docker-entrypoint.sh memcached   Up      11211/tcp
unsw_mysql_1      docker-entrypoint.sh --max ...   Up      0.0.0.0:32772->3306/tcp, 33060/tcp
unsw_nginx_1      /usr/local/bin/entrypoint.sh     Up      80/tcp, 0.0.0.0:32775->8082/tcp
unsw_syslog_1     /usr/sbin/syslog-ng -e -F  ...   Up      5514/tcp, 5601/tcp
unsw_unison_1     /sbin/tini -- /entrypoint.sh     Up      0.0.0.0:32768->5000/tcp
unsw_varnish_1    /usr/local/bin/entrypoint.sh     Up      0.0.0.0:32776->8081/tcp

**Comment by otakumike** [comment]
Thanks as always for the bug report Ben! I'm going to close this issue now as we've fixed this in 1.6 and will be releasing it in the next week.
