### ISSUE TITLE
Unable to `tok up` if an OpenVPN connection is running

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#106]
**What happened**:
Tried running `tok up -d` and received a "could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network" at which point the tok up operation exited.

**What you expected to happen**:
`tok up` completes running normally with out errors.

**How to reproduce it (as minimally and precisely as possible)**:
* Start an OpenVPN connection.
* Start a Tokaido project: `tok up`

**Anything else we need to know?**:
n/a

**Environment**:
- Tokaido version (use `tok version`): v1.5.0
- Drupal version: 8
- Operating system and version: Linux Mint 19.1

**Additional context**
n/a

**Comment by otakumike** [comment]
Could you please send us the output of `tok up -d` (you can send this private)?

But, I suspect this is going to be a Docker issue rather than a Tokaido issue, as all our networking stuff is just wrapped around Docker itself. I can take a closer look with the debug log, however.

**Comment by garrettw** [comment]
I think I've come across this error using Lando before. What it means is that you have too many Docker containers registered on the system. Try deleting some and then create this one again -- I bet it will work.

**Comment by otakumike** [comment]
I'm going to close this issue as it appears to have gone stale. Ben, if you're still having this problem please let us know and we can re-open.
