### ISSUE TITLE
Fpm container reports for missing sendmail

### ISSUE THREAD

**Issue by avakorin** [ironstar-io/tokaido#115]
**What happened**:
All fpm containers report for missing sendmail.

**How to reproduce it**:
1. Start new project, e. g. `tok new d8 --profile standard`
2. Create new user via Drupal admin panel with checked `Notify user of new account`
3. See logs of `d8_fpm_1` container

**Environment**:
- Tokaido version: v1.6.1
- Drupal version: Drupal 7/8
- Operating system and version: macOS Mojave 10.14.3

**Container logs**
```bash
config value 'PHP_MAX_INPUT_TIME'         :: 180
config value 'PHP_MAX_INPUT_VARS'         :: 1000
config value 'PHP_MEMORY_LIMIT'           :: 512M
config value 'PHP_DISPLAY_ERRORS'         :: yes
config value 'PHP_DISPLAY_STARTUP_ERRORS' :: Off
config value 'PHP_LOG_ERRORS'             :: On
config value 'PHP_LOG_ERRORS_MAX_LEN'     :: 1024
config value 'PHP_IGNORE_REPEATED_ERRORS' :: Off
config value 'PHP_IGNORE_REPEATED_SOURCE' :: Off
config value 'PHP_REPORT_MEMLEAKS'        :: On
config value 'PHP_POST_MAX_SIZE'          :: 64M
config value 'PHP_DEFAULT_CHARSET'        :: UTF-8
config value 'PHP_FILE_UPLOADS'           :: On
config value 'PHP_UPLOAD_MAX_FILESIZE'    :: 64M
config value 'PHP_MAX_FILE_UPLOADS'       :: 20
config value 'PHP_ALLOW_URL_FOPEN'        :: On
config value 'DOCROOT'                    :: /web
[18-Mar-2019 20:47:14] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[18-Mar-2019 20:47:14] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[18-Mar-2019 20:47:14] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[18-Mar-2019 20:47:14] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[18-Mar-2019 20:47:14] NOTICE: fpm is running, pid 106
[18-Mar-2019 20:47:14] NOTICE: ready to handle connections
[18-Mar-2019 20:47:14] NOTICE: systemd monitor interval set to 10000ms
[18-Mar-2019 20:54:22] WARNING: [pool www] child 109 said into stderr: "sh: 1: /usr/sbin/sendmail: not found"
```

**Comment by otakumike** [comment]
Thanks for the report @avakorin! Will look at adding sendmail in 1.7 due out in a few weeks. 

In the interim, you might be able to do what you need with [the Mailhog container](https://docs.tokaido.io/tokaido/mailhog)?

**Comment by avakorin** [comment]
Our project uses drupal built-in mail system, so I'll wait for sendmail :)

**Comment by otakumike** [comment]
This has been rolled into the 1.8 release happening shortly. 

We're using ssmtp in both the fpm and admin containers to auto-forward email to mailhog, which you'll see there if it's enabled. 

Here's a sample of an email in mailhog coming through just after `drush site-install` is run: 

![image](https://user-images.githubusercontent.com/9390978/57577214-b240bb00-74b5-11e9-8a54-de2992521eee.png)

Thanks again for the report @avakorin - I really appreciate you taking the time to give us feedback 🥇
