### ISSUE TITLE
Make Docker Volumes the recommended default

### ISSUE THREAD

**Issue by otakumike** [ironstar-io/tokaido#129]
Tokaido 1.7 introduced using Docker volumes instead of the Fusion Sync service. This made certain disk-heavy operations take longer (such as composer install) but has remarkably improved stability, especially for new users. 

In Tokaido 1.8, we will make Docker Volumes the default. We also want to slightly re-work the global config file so that it's not as confusing for new users

Acceptance Criteria: 
- [ ] If the user does not have a `~/.tok/global.yml` file and they are on MacOS, prompt them to choose their sync strategy. This prompt should include the advantages and disadvantages of each. 'docker' should be the recommended default option
- [ ] If the user does not have a `~/.tok/global.yml` file and they are on Linux, just set the sync strategy to `unison` without prompting (since only Unison works on Linux)
- [x] If the user has a legacy `~/.tok/config.yml` file, delete it. This file was too easily confused with `.tok/config.yml` in the repo. 
- [ ] Make it possible for the user to change the sync strategy using `tok config`
- [ ] Add a page in the Tokaido documentation explaining the differences in sync strategies.

**Comment by garrettw** [comment]
Do you find that overall D8 performance is still acceptable over Docker volumes? I believe Lando is using the same approach for storage/sync, and the poor D8 performance we've experienced is the primary reason we've started moving away from Lando to a dedicated dev server on the LAN.

**Comment by otakumike** [comment]
When we first (reluctantly) implemented docker volume support, I didn't think I'd be using it personally. But I have to admit it's become my preferred option because of the reliability: Unison just causes too many issues.

What we've found is that when using Docker Volumes, disk operations take longer but everything else works pretty much at the same speed. I did some tests on this when doing some of the more intensive tasks:

for clarity:
- Fusion Sync is where we run Unison inside a Docker container and use Docker Volume, it's more reliable than client-side Unison from before Tokaido 1.6, but still has reliability issues when Unison inexplicably consumes 100% CPU and forces you to restart Docker)
- Client-side Unison is the older style, where MacOS or Linux run a Unison client on the host OS

`drush site-install`:

- With Client-side Unison: 0m24.180s
- With Docker Volume Mount: 1m27.244s
- With Fusion Sync: 0m47.598s

`composer outdated "drupal/*"`:

- With Client-side Unison: 1m24.450s
- With Docker Volume Mount: 1m55.933s
- With Fusion Sync: 1m10.737s

`rm -rf vendor`:

- With Client-side Unison: 0m0.001s
- With Docker Volume Mount: 0m10.890s
- With Fusion Sync: 0m0.264s

`composer install`:

- With Client-side Unison: 1m40.330s
- With Docker Volume Mount: 5m2.133s
- With Fusion Sync: 2m6.671s

That last one is the most significant - `composer install` is ~4 times slower with docker volumes. That's pretty bad, but what we're finding with most users on 1.7 is that they prefer the stability of Docker Volumes and would rather keep that stability rather than trade it off for improved performance on operations they don't do every day. 

Ultimately it's a personal preference, so that's why we're going to give MacOS users the ability to choose between them when they first run `tok up` on a new system. But otherwise, I think having Docker Volumes as the default is the best way of driving up Tokaido adoption, otherwise Tokaido itself seems unstable.

**Comment by otakumike** [comment]
After discussing this with @yjimk we've opted to just silently make Docker the default, while letting pro users switch back to using Unison if they want to by modifying the `~/.tok/global.yml` file

The rationale is that providing a complex explanation of competing sync strategies is just going to alienate and confuse new users for what is ultimately a simple decision - new users should use Docker volumes because it doesn't get in the way. 

This changes the prompting requirements a little bit.
