### ISSUE TITLE
Restore Linux Support

### ISSUE THREAD

**Issue by otakumike** [ironstar-io/tokaido#133]
As part of the migration to the Fusion sync service in Tokaido 1.6, we removed Linux support. As luck would have it, we need to re-add this service in order to run Tokaido in CircleCI (as part of the updated `tok test` functionality planned for Tokaido 1.9. 

Acceptance Criteria: 
- [x] Re-add Linux support in the Tokaido CLI
- [x] Re-add the Unison sync service and systemctl support for Linux users 
- [x] Ensure that Linux users use the Unison sync service, while MacOS users can choose between Unison, Fusion, and Docker
- [x] Ensure that there is a documentation page explaining the sync strategies, advantages and disadvantages of each, and which one we recommend
- [ ] Verify that Tokaido can now run inside CircleCI when using the `machine` executor.

**Comment by garrettw** [comment]
So Unison is more reliable on Linux?

**Comment by otakumike** [comment]
Sadly, Unison is still a bit buggy no matter where we run it. But we can only effectively run client-side Unison on Linux because of user ids. 

When you use docker volume mounts on MacOS, for example, the uid and gid of each file are reset because the docker volume mount doesn't preserve them. This makes it easy to assign the uid/gid via the container. Of all the Tokaido containers, only the SSH container runs as root, otherwise we really want to avoid that. 

On Linux, Docker runs natively and not via a VM, so Docker volume mounts are direct translations from the host. This means that the uid:gid are linked directly.

As a really simple example, if you as a Linux user have uid 1000 and create a Drupal project, all your files are owned by uid 1001. When Tokaido starts, it runs with uid 1001 (and some others) and can't access your files because it's not the owner. Likewise, if you create a file inside the Tokaido environment, you can't access it on your own host. 

Other tools work around this problem by building the container environment on the fly (using docker build) using your uid and making you the owner of all the files. We don't do this at the moment because we choose to pre-build all the containers and make absolutely certain they match our hosted environments (if you run docker build locally, you might get different versions than we get when we build for production, for instance). 

Using Unison on Linux solves this problem because it allows us to change the uid/gid of the files as they're synced between host and client.

**Comment by otakumike** [comment]
gotta bump this to 1.9 as we're out of time for 1.8
