### ISSUE TITLE
Tok up on new project not creating .tok/config.yml file

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#138]
**What happened**:
Set up a branch new Drupal 8 project using Drupal composer template. Then started `tok up`. However the FPM and nginx containers failed to load. I checked the nginx and fpm container logs and they reported that the .tok/config.yml file was missing. I checked the .tok/ folder in the project and noted that no config.yml file had been created. After manually creating the config.yml file, I was able to successfully start the fpm and nginx containers.

**What you expected to happen**:
On `tok up` the pfm and nginx containers should start.

**How to reproduce it (as minimally and precisely as possible)**:
- create new drupal project
- in project root directory run `tok up`

**Anything else we need to know?**:
n/a

**Environment**:
- Tokaido version (use `tok version`): v1.7.1
- Drupal version: 8.x
- Operating system and version: OSX 10.14.4

**Additional context**
n/a

**Comment by otakumike** [comment]
Thanks for the report Ben. I'll fix this next week and do a new release.
