### ISSUE TITLE
`tok test` and PHP Unit compatibility

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#139]
**What happened**:
Not sure if this is an actual bug, but wasn't sure where to put it.

When running `tok test` it reports "...Tokaido detected you're running version 4.8.36 of PHPUnit, which isn't compatible with Drupal Nightwatch. ... Would you like us to attempt to update it for you automatically with composer? (Y/n): Y..."

After tok test completes I noticed that PHPunit version 7 is installed. 

![Screen Shot 2019-05-03 at 4 31 35 pm](https://user-images.githubusercontent.com/1292616/57122478-f8fd2980-6dc0-11e9-86a1-cc802331ec3b.png)

If I remember correctly, Drupal 8 is not compatible with PHPunit 7. This is due to Drupal 8's reliance on Symfony 3. 

Wondering if this will be a problem or potentially break things? Just thought I would mention it.

**What you expected to happen**:
n/a

**How to reproduce it (as minimally and precisely as possible)**:
* Run `tok test`
* Let Tokaido update PHP unit
* Check projects `composer.json` file. PHPunit version number had been changed to `^7`

**Anything else we need to know?**:
n/a

**Environment**:
- Tokaido version (use `tok version`): 1.7.1
- Drupal version: 8
- Operating system and version: OSX 10.14.4

**Additional context**
n/a

**Comment by Benjen** [comment]
I looked into it a bit further and found the following in Drupal's `core/tests/bootstrap.php`:

"... PHPUnit testing framework version 6 or greater is required when running on PHP 7.0 or greater. Run the command 'composer run-script drupal-phpunit-upgrade' in order to fix this. ..."

So may not be an issue after all.

**Comment by yjimk** [comment]
Hey Ben, Thanks for raising this one.

Really tricky to tell what the right course of action is here at the moment. PHPUnit 6 was deprecated in February 2019, but it's still listed as the version in use when coupled with PHP 7.2 on the official Drupal site. https://www.drupal.org/docs/8/phpunit

There's also an issue raised to bump support to v7, and even v8 on the forum too, but it doesn't look like there's a lot of action on that. https://www.drupal.org/project/drupal/issues/2950132

Running the not officially supported version of PHPUnit may cause breakage, not going to be certain until there have been some tests run against it. Safest course of action might be to just drop to 6.5 in the mean time.

@otakumike do you have an opinion on this?

**Comment by Benjen** [comment]
Hi @yjimk , I think the safer option might be to go with PHP Unit 6.5. Admittedly I am also not such an expert when it comes to testing so also not sure what or how things might break with PHP Unit v7. From what I can tell Drupal 8 should work with PHP 6.5 (for example it is a listed dependency of the webflo/drupal-core-require-dev used by [Drupal composer template project](https://github.com/drupal-composer/drupal-project): `"phpunit/phpunit": "^4.8.35 || ^6.5"`).

Out of curiousity that is meant to be a [script](https://github.com/drupal/drupal/blob/8.7.x/core/tests/README.md#running-nightwatch-tests) (`drupal-phpunit-upgrade`) provided by Drupal for updating PHP Unit for Nightwatch compatibility. Is it that script which is being used to upgrade PHP Unit when running `tok test`?

**Comment by otakumike** [comment]
Sounds like 6.5 is the way to go for now...

**Comment by yjimk** [comment]
Yeah, I think you're both right, I shouldn't have used v7 initially. Maybe we will be raising the same issue this time next year when Drupal 9 is released with PHPUnit 7, due for deprecation in Feb 2020.

Tokaido isn't using `drupal-phpunit-upgrade` under the hood, from memory I couldn't quite get it working at the time, so went another way around.

**Comment by otakumike** [comment]
@Benjen that should be in place now. You can test it now using the edge version (download via the 'releases' page' or wait until we release v1.8 later this week.
