### ISSUE TITLE
Enable use of tok commands from children directories

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#15]
A nice to have would be the ability to run tok commands from sub-directories within the project. For example, if I was working in the drupal sites directory and ran tok open, then it would open the site in the browser, rather than having to first switch back to the project root directory which contains the docker-compose.tok.yml file.

**Comment by otakumike** [comment]
This is a really great suggestion. I'm going to ask Jimmy to take a look at this before our beta release if he can.

**Comment by yjimk** [comment]
Hey @Benjen, thanks for opening this issue! It's a good call, definitely a bit annoying having to cd back the to project root all the time.

PR coming shortly to address this. :D

**Comment by otakumike** [comment]
Hi @Benjen - just wanted to let you know this issue will be in the next release, scheduled for Sunday. Thanks for the great suggestion :)
