### ISSUE TITLE
Confusion on what y/n options do on automatic settings.php configuration

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#16]
Minor issue, but sometimes I find the following a bit confusing when running `tok up`:

    Tokaido can now create database connection settings for your site.
    Should Tokaido add the file /Users/bgunn/Documents/dev/tokaido/unsw-teaching- 
    d8/web/sites/default/settings.tok.php and reference it from 'settings.php'?
    
    If you prefer not to do this automatically, we'll show you database connection
    settings so that you can configure this manually. (Y/n):

Sometimes I find myself having to re-read this to understand what I am agreeing to when I select either 'y' or 'n'. Perhaps we could change it to something like this:

    Tokaido can now create database connection settings for your site by adding the file 
    /Users/bgunn/Documents/dev/tokaido/unsw-teaching-d8/web/sites/default/settings.tok.php and 
    reference it from 'settings.php'.  If you prefer not to do this automatically, we'll show you database 
    connection settings so that you can configure this manually. 
    
    Let Tokaido automatically configure your database connection settings (Y/n):

**Comment by otakumike** [comment]
Thanks for the suggestion Ben. I've included a slightly re-worded version of your suggestion in our next release.
