### ISSUE TITLE
Error installing Unison-fsmonitor during Tokaido installation on Linux Mint 19.0

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#17]
**What happened**:
Have tried to install Tokaido on Linux Mint 19.0 using instructions on [getting started](https://tokaido.io/docs/getting-started/) page. System is using Unison 2.48.4 so have been following instructions for installing unison-fsmonitor for Unison 2.48.4. 

Upon running `make` command (`make UISTYLE=text NATIVE=true STATIC=true`), I receive the following error:

    /bin/sh: 1: ocamlc: not found
    /bin/sh: 1: ocamlc: not found
    make -C src mkProjectInfo
    make[1]: Entering directory '/tmp/unison-2.48.4/src'
    /bin/sh: 1: ocamlc: not found
    /bin/sh: 1: ocamlc: not found
    ocamlc -o mkProjectInfo unix.cma str.cma mkProjectInfo.ml
    make[1]: ocamlc: Command not found
    make[1]: *** No rule to make target 'mkProjectInfo', needed by 'Makefile.ProjectInfo'.  Stop.
    make[1]: Leaving directory '/tmp/unison-2.48.4/src'
    make -C src
    make[1]: Entering directory '/tmp/unison-2.48.4/src'
    /bin/sh: 1: ocamlc: not found
    /bin/sh: 1: ocamlc: not found
    ocamlc -o mkProjectInfo unix.cma str.cma mkProjectInfo.ml
    make[1]: ocamlc: Command not found
    UISTYLE = text
    Building for Unix
    NATIVE = true
    THREADS = false
    STATIC = true
    OSTYPE =
    OSARCH = Linux
    ocamlopt: lwt/lwt.mli ---> lwt/lwt.cmi
    ocamlopt -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I             
    system/generic -I lwt/generic -c /tmp/unison-2.48.4/src/lwt/lwt.mli
    make[1]: ocamlopt: Command not found
    Makefile.OCaml:426: recipe for target 'lwt/lwt.cmi' failed
    make[1]: *** [lwt/lwt.cmi] Error 127
    make[1]: Leaving directory '/tmp/unison-2.48.4/src'
    Makefile:11: recipe for target 'src' failed
    make: *** [src] Error 2

Turns out issue is due to missing OCaml compiler. Was able to install compiler and associated libraries using `apt install ocaml`. After installing the compiler the `make` command was able to run successfully, thus enabling me to complete the Tokaido installation process.

**Environment**:
- Tokaido version (use `tok version`): vedge-7-g9056285 (build date: 2018-08-12T20:36:28Z)
- Drupal version: Drupal 8
- Operating system and version: Linux Mint 19.0

**Comment by otakumike** [comment]
Thanks Ben! I've updated our Getting Started docs to make it clear that Ocaml is an install dependency. Those will be out in the next few days.
