### ISSUE TITLE
Unable to start Tokaido on Linux Mint 19.0

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#18]
**What happened**:
I am unable to successfully run `tok up` on Linux Mint 19.0. After running `tok up` I receive the following message:

    Creating a background process to sync your local repo into the Tokaido environment
    2018/08/13 20:35:02 Unable to start the sync service: exit status 5

**What you expected to happen**:
`tok up` should complete without errors

**How to reproduce it (as minimally and precisely as possible)**:
* Install Tokaido on Linux Mint 19 following get started instructions
* run `tok up`

**Anything else we need to know?**:
Prerequisites installed on system are:
* Docker: version 18.03.1-ce, build 9ee9f40
* Unison: 2.48.4
* fsmonitor: 0.1
* unison-fsmonitor installed as per instructions for Unison 2.48.4 on getting started page

Running `tok -d up` I get the following output:

    🚀  Tokaido is starting up!
    2018-08-13T10:27:04Z: Running command: 'unison -version'
    2018-08-13T10:27:04Z: unison version 2.48.4

    2018-08-13T10:27:04Z: Running command: 'unison -version'
    2018-08-13T10:27:04Z: unison version 2.48.4

    2018-08-13T10:27:04Z: Running command: 'docker-compose -f /home/bgunn/dev/tokaido/cca8/docker-compose.tok.yml up -d unison'
    Recreating cca8_unison_1 ... done

    2018-08-13T10:27:22Z: Running command: 'docker-compose -f /home/bgunn/dev/tokaido/cca8/docker-compose.tok.yml port unison 5000'
    2018-08-13T10:27:23Z: 0.0.0.0:32771

    2018-08-13T10:27:23Z: Running command: 'systemctl --user status tokaido-sync-cca8.service'
    2018-08-13T10:27:23Z: exit status 4
    exit status 4
    2018-08-13T10:27:23Z: Running command: 'systemctl --user status tokaido-sync-cca8.service'
    2018-08-13T10:27:23Z: exit status 4
    exit status 4
    2018-08-13T10:27:23Z: Running command: 'unison cca8 -watch=false'
    2018-08-13T10:28:18Z: Contacting server...
    Connected [//bgunn-H97-Gaming-3//home/bgunn/dev/tokaido/cca8 -> //e6790cb5ef11//tokaido/site]
    Looking for changes
    Warning: No archive files were found for these roots, whose canonical names are:
	    /home/bgunn/dev/tokaido/cca8
	    //e6790cb5ef11//tokaido/site
    This can happen either
    because this is the first time you have synchronized these roots, 
    or because you have upgraded Unison to a new version with a different
    archive format.  

    Update detection may take a while on this run if the replicas are 
    large.

    Unison will assume that the 'last synchronized state' of both replicas
    was completely empty.  This means that any files that are different
    will be reported as conflicts, and any files that exist only on one
    replica will be judged as new and propagated to the other replica.
    If the two replicas are identical, then no changes will be reported.

    If you see this message repeatedly, it may be because one of your machines
    is getting its address from DHCP, which is causing its host name to change
    between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
    environment variable for advice on how to correct this.

    Donations to the Unison project are gratefully accepted: 
    http://www.cis.upenn.edu/~bcpierce/unison

      Waiting for changes from server                                       
    Reconciling changes
    Nothing to do: replicas have been changed only in identical ways since last sync.
    Fatal error: No file monitoring helper program found

    🔄  Creating a background process to sync your local repo into the Tokaido environment
    2018-08-13T10:28:18Z: Running command: 'systemctl --user daemon-reload'
    2018-08-13T10:28:18Z: Running command: 'systemctl --user start tokaido-sync-cca8.service'
    2018-08-13T10:28:18Z: exit status 5
    2018/08/13 20:28:18 Unable to start the sync service: exit status 5

**Environment**:
- Tokaido version (use `tok version`):vedge-7-g9056285 (build date: 2018-08-12T20:36:28Z)
- Drupal version: Drupal 8
- Operating system and version: Linux Mint 19

**Comment by otakumike** [comment]
Ben, could you please send me the contents of the systemd service file that's failing? 

`cat ~/.config/systemd/user/tokaido-sync-cca8.service` 

Also, if you can try and start the systemd service and then get the output from the journal that might help too:

`systemctl --user start tokaido-sync-cca8.service`
`journalctl --user -u tokaido-sync-cca8.service`

Could you also confirm if the foreground sync process works if you run: `tok watch` ?

Thanks mate,
Richo

**Comment by otakumike** [comment]
Thanks Ben! I think in fact there are two problems here. 

First, systemd can't find your service config file. There might be one of two reasons for this:

- Linux Mint doesn't use the default systemd user file location (`.config/systemd/user`). 
There's a hidden Tokaido config setting that you can use to modify this path: 
```
tokaido:
  systemdPath: /path/to/where/linux/mint/wants/user/service/files
```

But setting this value will break the configuration for anyone else who uses the same repo (as Tokaido configs are global). I wouldn't recommend changing this value, though. 

OR
- The daemon-reload process didn't happen for some reason, so that systemd hasn't read the new file. You can do this manually: `systemctl daemon-reload` and then try starting the service again. 

To be honest, I'm not confident that either of these will fix your problems (daemon-reload is run by Tokaido automatically). You might have to just use the foreground sync service on Linux Mint, which brings us to your other problem:

Linux has a restriction on the "amount of inotify watchers", and it looks like your system has hit this. It's pretty easy to change this, though. [This page does a great job of explaining this](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers).

If you can try increasing your inotify watchers (you may need to reboot), and running `tok up` again, let me know how you go. If the background service still fails, try `tok watch` again. It _should_ work with the inotify watcher limit increased.

**Comment by otakumike** [comment]
I've documented this in our FAQ now: https://tokaido.io/docs/faq/

**Comment by Benjen** [comment]
I have increased the number of inotify watchers to 524288. After rebooting I checked to confirm the inotify watchers are correct then ran `tok up`. Still getting errors. 

    2018-08-25T10:58:06Z: Running command: 'unison -version'
    2018-08-25T10:58:06Z: unison version 2.48.4

    2018-08-25T10:58:06Z: Running command: 'unison -version'
    2018-08-25T10:58:06Z: unison version 2.48.4

    2018-08-25T10:58:06Z: Running command: 'docker-compose -f /home/bgunn/dev/tokaido/cca8/docker-compose.tok.yml up -d unison'
    Recreating cca8_unison_1 ... done

    2018-08-25T10:58:24Z: Running command: 'docker-compose -f /home/bgunn/dev/tokaido/cca8/docker-compose.tok.yml port unison 5000'
    2018-08-25T10:58:25Z: 0.0.0.0:32771

    2018-08-25T10:58:25Z: Running command: 'systemctl --user status tokaido-sync-cca8.service'
    2018-08-25T10:58:25Z: exit status 4
    exit status 4
    2018-08-25T10:58:25Z: Running command: 'systemctl --user status tokaido-sync-cca8.service'
    2018-08-25T10:58:25Z: exit status 4
    exit status 4
    2018-08-25T10:58:25Z: Running command: 'unison cca8 -watch=false'
    2018-08-25T10:59:17Z: Contacting server...
    Connected [//3a9418cc9fb0//tokaido/site -> //bgunn-H97-Gaming-3//home/bgunn/dev/tokaido/cca8]
    Looking for changes
    Warning: No archive files were found for these roots, whose canonical names are:
	    /home/bgunn/dev/tokaido/cca8
	    //3a9418cc9fb0//tokaido/site
    This can happen either
    because this is the first time you have synchronized these roots, 
    or because you have upgraded Unison to a new version with a different
    archive format.  

    Update detection may take a while on this run if the replicas are 
    large.

    Unison will assume that the 'last synchronized state' of both replicas
    was completely empty.  This means that any files that are different
    will be reported as conflicts, and any files that exist only on one
    replica will be judged as new and propagated to the other replica.
    If the two replicas are identical, then no changes will be reported.

    If you see this message repeatedly, it may be because one of your machines
    is getting its address from DHCP, which is causing its host name to change
    between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
    environment variable for advice on how to correct this.

    Donations to the Unison project are gratefully accepted: 
    http://www.cis.upenn.edu/~bcpierce/unison

      Waiting for changes from server                                       
    Reconciling changes
    Nothing to do: replicas have been changed only in identical ways since last sync.
    Fatal error: No file monitoring helper program found


    🔄  Creating a background process to sync your local repo into the Tokaido environment
    2018-08-25T10:59:17Z: Running command: 'systemctl --user daemon-reload'
    2018-08-25T10:59:17Z: Running command: 'systemctl --user start tokaido-sync-cca8.service'
    2018-08-25T10:59:17Z: exit status 5

Tried running `tok watch`:

    Watching your files for changes and synchronising with your container
    Please keep this command running in order to retain sync
	    
    Contacting server...
    Connected [//5e23321eb400//tokaido/site -> //bgunn-H97-Gaming-3//home/bgunn/dev/tokaido/cca8]
    Looking for changes
    Warning: No archive files were found for these roots, whose canonical names are:
	    /home/bgunn/dev/tokaido/cca8
	    //5e23321eb400//tokaido/site
    This can happen either
    because this is the first time you have synchronized these roots, 
    or because you have upgraded Unison to a new version with a different
    archive format.  

    Update detection may take a while on this run if the replicas are 
    large.

    Unison will assume that the 'last synchronized state' of both replicas
    was completely empty.  This means that any files that are different
    will be reported as conflicts, and any files that exist only on one
    replica will be judged as new and propagated to the other replica.
    If the two replicas are identical, then no changes will be reported.

    If you see this message repeatedly, it may be because one of your machines
    is getting its address from DHCP, which is causing its host name to change
    between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
    environment variable for advice on how to correct this.

    Donations to the Unison project are gratefully accepted: 
    http://www.cis.upenn.edu/~bcpierce/unison

      Waiting for changes from server                                       
    Reconciling changes
    Nothing to do: replicas have been changed only in identical ways since last sync.
    Looking for changes
      Waiting for changes from server
    Reconciling changes
    Nothing to do: replicas have not changed since last sync.
    Looking for changes
      Waiting for changes from server
    Reconciling changes
    Nothing to do: replicas have not changed since last sync.
    Fatal error: Lost connection with the server

**Comment by Benjen** [comment]
@otakumike I am pleased to say that Tokaido is now working on my Linux Mint 19.1 box :-D

Unfortunately I can't tell you why it now works. I didn't do anything in particular. Just thought I would give it another go and hey presto it worked :S

**Comment by otakumike** [comment]
Glad it's working! Thanks Ben
