### ISSUE TITLE
Drush container line wrap issue

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#186]
**What happened**:
Get an issue where the command line appears to wrap back on itself when using the command line within the Drush container (see screencast below)

[tokaido_iterm2_cli_issues.mp4.zip](https://github.com/ironstar-io/tokaido/files/3357980/tokaido_iterm2_cli_issues.mp4.zip)

**What you expected to happen**:
Text should wrap cleanly to new line.

**How to reproduce it (as minimally and precisely as possible)**:
See screencast.

**Anything else we need to know?**:
- Using iTerm2 (v3.2.9) as the terminal emulator.
- Issue only occurs with the Drush container. Does not occur in host system.

**Environment**:
- Tokaido version (use `tok version`): v1.9.2
- Drupal version: 8.6.16
- Operating system and version: OSX Mojave 10.14.5

**Additional context**
N/A

**Comment by otakumike** [comment]
Thanks Ben! We'll try to sort this out in the next release (likely later this month/early August)

**Comment by otakumike** [comment]
This should be fixed now in the latest 'edge' containers, so next time you run `tok up` it'll pull those down. 

Bash prompts are messy things so it might not be perfect, but hopefully it'll be a bit better. I'll leave this Issue open for now, so please let us know if you still see problems?

**Comment by otakumike** [comment]
Ben has confirmed in Slack that this is working better now, so I'll close this issue.
