### ISSUE TITLE
Selenium (W3C Webdriver) server integration

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#19]
**Is your feature request related to a problem? Please describe.**
Not really a problem but was thinking that it could be handy to have some testing related services available. For example [Nightwatch.js](http://nightwatchjs.org/) is an automated testing framework which used Node.js and W3C Webdriver (formerly Selenium). 

**Describe the solution you'd like**
Would be nice if one was able to enable a Selenium container on a project which would enable the use of testing framework such as Nightwatch.js. In the past I have heard that Java based Selenium can be tricking to get up and running on a server. I assume having a Selenium container would reduce this complexity.

**Describe alternatives you've considered**
Haven't considered alternatives.

**Additional context**
None

**Comment by otakumike** [comment]
This is definitely something we want to incorporate, but unfortunately I have never worked with test in Drupal. I'm going to leave this issue open for us to look at in the future, but it's probably going to be a few weeks (or even months) before we can look into it. 

Ideally I'd love to wrap this up as a command like `tok test` that will run the tests in a container on-demand.

**Comment by otakumike** [comment]
Hey Ben,

In 1.4.0 we introduced the `tok test` command. This will auto-provision the nightwatch test suite which seems to be the recommended and most-official Drupal testing framework. 

The only caveat is that this is only part of Drupal core 8.6 and up. Given that this is the path of least resistance us, and that there are too many competing and non-official test frameworks, we're going to leave our support coverage at just Nightwatch. I hope that doesn't cause you too many headaches! 

I'm going to close this now as we consider the feature implemented. The new functionality is documented over at our new Docs site if you want to check it out (although it's pretty light): https://app.developerhub.io/tokaido/1.5.0/tokaido/provisioning-nightwatch-tests
