### ISSUE TITLE
Support Acquia site factory (ASF) sites

### ISSUE THREAD

**Issue by eleonel** [ironstar-io/tokaido#228]
Acquia site factory have the own way to edit the settings.php file normally located in docroot/sites/default/settings.php

> When using Acquia Cloud Site Factory, you cannot directly modify your website’s settings.php file, but you can make changes to values in settings.php using hooks at the beginning and end of the settings.php file. [[Source]](https://docs.acquia.com/site-factory/extend/hooks/settings-php/)

After running `tok up` I can see some new lines inside the `settings.php` file:

```
/*
 * Generated by Tokaido
 */

if (file_exists($app_root . '/' . $site_path . '/settings.tok.php')) {
  include $app_root . '/' . $site_path . '/settings.tok.php';
}

/*
 * END Generated by Tokaido
 */
```

One way to solve this is manually adding that lines as a hook file inside the `factory-hooks/post-settings-php` folder but this is only relevant for ASF sites so that's why I need to check if anyone have any other idea.

Thanks.

**Comment by otakumike** [comment]
If you make this change in `factory-hooks/post-settings-php` does the site work as you expect? I'm curious to know if there are other unique things we'd have to change to support ASF

**Comment by eleonel** [comment]
Hi @otakumike 

yes, but after working a while with the ACSF repository structure I'm thinking to don't use it as a working copy, I will use the repository as a deployment repository so I don't longer need this change.

ACSF repositories are very different than a normal drupal folder structure and you need to do so many unusual tricks to have a local dev environment.
