### ISSUE TITLE
tok stop doesn't stop all the containers

### ISSUE THREAD

**Issue by eleonel** [ironstar-io/tokaido#229]
**What happened**:
I ran `tok stop` while I had all the Tokaido containers running.

![Screenshot from 2020-01-25 17-18-23](https://user-images.githubusercontent.com/1221946/73118404-0da8cf80-3f97-11ea-90c9-58673cbaef2b.png)

But I can see some of the containers are still running and this is an issue because then if you want to change to another git branch you may received some: `warning: unable to unlink ... Permission denied`

**Environment**:
- Tokaido Version: v1.12.1
- Build Date:      2019-11-26T22:25:33Z
- Compiler:        go1.13.4
- Platform:        linux/amd64
- OS:                Ubuntu 19.04

**Comment by otakumike** [comment]
Hi Eleo,

These containers are part of the 'proxy' service, which presents the https://*.local.tokaido.io:5154 URL. It's normal for these to keep running even if you don't have any Tokaido environments running. 

Can you provide a little more detail about how you got the 'unable to unlink' error? Note that most Tokaido commands can be run with a `-d` flag to get some extra debug output.

**Comment by eleonel** [comment]
Hi @otakumike 

Sorry the problem that I have with the unable to unlink it was just a permissions error, not related to those Tokaido containers running.
