### ISSUE TITLE
Support Apple Silicons with mariadb while Docker RC has no mysql image

### ISSUE THREAD

**Issue by hasi** [ironstar-io/tokaido#244]
I was trying to spin up new local Drupal 9 environment on my Apple M1 Macbook and fails due to lack of mysql support from Docker Desktop RC version I guess. Is there anyway I can use mariadb instead with available tokaido images, so that Docker Desktop RC will support the installation?

Below is the error:
   ~/Sites  tok new                                     1 ✘  22:43:41 

Enter a directory name for your new project: drupal9
Please choose the Drupal template you'd like to launch
drupal9-umami

🍚  Launching new project [drupal9] with Drupal template [drupal9-umami]
downloading package from [https://downloads.tokaido.io/packages/drupal9-standard.tar.gz]
    Unpacked the install template

🚀  Tokaido is starting up!
🚇  Found a Drupal 8 or Drupal 9 site
🏯  Generating a new docker-compose.tok.yml file
🔐  Configuring TLS Certificates
🚅  Starting your Drupal environment
Tokaido encountered a fatal error and had to stop at command 'docker-compose -f /Users/hasitha/Sites/drupal9/docker-compose.tok.yml up --remove-orphans -d'
Pulling mysql (mysql:5.7)...
Docker Compose is now in the Docker CLI, try `docker compose up`

5.7: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
2021/04/14 22:44:24 exit status 1

**Comment by ironmike-au** [comment]
Yes, you can change to mariadb by running `tok config-set database engine mariadb` and then re-running `tok up`

We haven't had access to an M1 mac to test Tokaido on so I'm not sure if you will run into any other problems, however. Please let us know if you do!

**Comment by hasi** [comment]
Thanks Mike, 

As you suspected, now it's throwing more. I think this time it's drush related. Please see below.

   ~/Sites/drupal9    master ?5  tok config-set database engine mariadb                             ✔  20:01:12 
   ~/Sites/drupal9    master ?5  tok up                                                             ✔  20:04:08 

🚀  Tokaido is starting up!
🔐  Configuring TLS Certificates
🚅  Starting your Drupal environment
Tokaido encountered a fatal error and had to stop at command 'docker-compose -f /Users/hasitha/Sites/drupal9/docker-compose.tok.yml port drush 22'
No container found for drush_1
2021/04/15 20:06:07 exit status 1
