### ISSUE TITLE
Can't upgrade to v1.1.0 on OSX

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#33]
**What happened**:
When I try to upgrade from Tokaido v1.0.0 => v1.1.0 on OSX it says "Error: ironstar-io/tap/tokaido macos already installed"

**What you expected to happen**:
Expect to be able to update Tokaido from v1.0.0 => v1.1.0

**How to reproduce it (as minimally and precisely as possible)**:
* run `brew update`
* run `brew upgrade tokaido`

**Anything else we need to know?**:
N/A

**Environment**:
- Tokaido version (use `tok version`): v1.0.0
- Drupal version: Drupal 7
- Operating system and version: OSX Sierra (v.10.12.6)

**Additional context**
![screen shot 2018-09-04 at 2 41 35 pm](https://user-images.githubusercontent.com/1292616/45010397-ad875580-b050-11e8-8aba-8a46a8ba621e.png)

**Comment by otakumike** [comment]
Hi @Benjen ! 

Thanks for opening this issue. I've found the issue and fixed it alongside our 1.1.1 update. 

`brew upgrade tokaido` has successfully worked for me. 

Cheers,
Mike
