### ISSUE TITLE
Run `tok version` outside of a Git repository

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#39]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently one can only run `tok` commands from  within an existing git repository. Would be nice if one could check the version of Tokaido from anywhere in the system. For example, today I updated Tokaido. I opened a terminal and updated using brew. Afterwards I went to confirm I have the latest version installed so run `tok version`, at which point I am informed "Tokaido needs to be run from inside a Git repository, but could not find one. Exiting..."

**Describe alternatives you've considered**
No

**Additional context**
N/A

**Comment by otakumike** [comment]
@yjimk I'll leave this one with you for now. As discussed, it's going to be tricky to implement with Cobra seemingly invoking initConfig() before doing anything else, but we need to resolve this for the `tok new` functionality as well.

**Comment by otakumike** [comment]
fixed and ready to go with 1.3.0. Thanks Ben!
