### ISSUE TITLE
Remove closing PHP tag from settings.tok.php file

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#40]
This is really minor but best practice would be not to close the PHP block in the `settings.tok.php` file (i.e. remove the `?>` from end of file.

From PHP manual [page](http://php.net/manual/en/language.basic-syntax.phptags.php):

> If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script.

**Comment by otakumike** [comment]
this is fixed in the upcoming 1.2.0 release. Thanks Ben!
