### ISSUE TITLE
Tokaido should activate and use mailhog by default

### ISSUE THREAD

**Issue by otakumike** [ironstar-io/tokaido#43]
Tokaido should enable the mailhog service by default, and configure the settings.tok.php file to use it for sending email. 

The `tok up` output should also point the user to this service so that they can view email send results.

**Comment by garrettw** [comment]
I don't need mailhog on every project, so I don't think I'd want it set up by default -- but the option is definitely needed.

**Comment by otakumike** [comment]
still unsure when/if this should be included, but to address Garrett's concerns - mailhog uses <5MB of memory and no CPU when enabled. 

I'm de-scoping this from 1.2.0 but will keep this issue open. The best scenario for this default SMTP config is one where mailhog is enabled and settings.tok.php provides a default SMTP server configuration that Drupal can take advantage of.

**Comment by otakumike** [comment]
This is now the default in Tokaido 1.9, along with de-activating memcache as a default. 

In the end we decided to turn this on by default because of the updates in 1.8 that enabled sending from sendmail to mailhog by default. Also, mailhog is so tiny that we decided we could use the footprint that memcache freed up.
