### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by garrettw** [ironstar-io/tokaido#52]
Would it be possible to allow users to choose between (at least) MySQL and MariaDB in the config file?

**Comment by otakumike** [comment]
Yup, that's definitely something we can look at implementing. I'll leave this ticket open until we can get to putting it in place.

**Comment by otakumike** [comment]
Hey @garrettw this feature will finally be out in the 1.9 release candidate early next week. I did a bunch of testing swapping between MariaDB and MySQL, as well as swapping versions of each, and it all seemed pretty stable. 

Thanks for your patience! I know it took us a while to get to this one...
