### ISSUE TITLE
Use global wildcard DNS resolution for local domain names to always point to 127.0.0.1

### ISSUE THREAD

**Issue by otakumike** [ironstar-io/tokaido#54]
Suggested by garrettw in Slack:

- Set up a new DNS name *.local.tokaido.io to auto-resolve to 127.0.0.1
- Update SSL certificate generator to create cert at *.local.tokaido.io
- Remove components that manipulate hosts file entries (except the ones that clean up with `tok destroy`

Thanks again Garrett!

**Comment by garrettw** [comment]
Any particular reasoning behind that domain choice? It's just a bit long. What about something intentionally invalid, such as `*.local.tok`?

**Comment by otakumike** [comment]
In order for this to work, it has to be a globally resolvable, valid domain name. We discussed using something like tok.site (similar to lndo.site) but I'd rather not use another domain in addition to tokaido.io.

**Comment by garrettw** [comment]
Oh ok, I didn't realize it had to be something valid. I actually thought `lndo.site` wasn't valid but I see now that it is, and they have registered it just to hold it.

**Comment by otakumike** [comment]
Yeah that's what makes it so clever. It's just got a wildcard resolution so that anything *.lndo.site gets resolved to 127.0.0.1. Really simple and super effective solution. Gotta hand it to the Lando guys on that one!

**Comment by otakumike** [comment]
This is implemented in the upcoming 1.2.0 release
