### ISSUE TITLE
Can't import SSL certificate into Firefox browser

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#61]
**What happened**:
I am unable to access the Tokaido site locally due to HTST error on Firefox (OSX v62.0.3). I have tried  importing the certificate into the browser as suggested on the [FAQ page](https://tokaido.io/docs/faq/). When I try to import the certificate I receive the following error:

"This personal certificate cannot be installed because you do not own the corresponding private key which was created when the certificate was requested"

**What you expected to happen**:
I expected the browser to accept the proxy_ca.pem file when importing it.

**How to reproduce it (as minimally and precisely as possible)**:
See attached screencast: 
[Import_TLS_cert_into_Firefox.mp4.zip](https://github.com/ironstar-io/tokaido/files/2448704/Import_TLS_cert_into_Firefox.mp4.zip)

**Anything else we need to know?**:

**Environment**:
- Tokaido version (use `tok version`): v1.2.0
- Drupal version: Drupal 7
- Operating system and version: OSX Sierra (10.12.6)

**Additional context**
None

**Comment by otakumike** [comment]
Hey @BenG!

Amazing bug report again, as always. Thanks!

I believe this will work if you choose the "Authorities" tag before clicking the import option. Can you give that a try and let me know? 

Cheers,
Richo
