### ISSUE TITLE
Duplicate confirmation dialog when using `tok destroy`

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#7]
**What happened**:
When I run `tok destroy` I have to confirm twice that I am aware that the operation will destroy the database.

**What you expected to happen**:
Should only have to confirm once. This worked correctly in v0.0.10

**How to reproduce it (as minimally and precisely as possible)**:
Run `tok destroy` on an existing running tok instance

**Anything else we need to know?**:
n/a

**Environment**:
- Tokaido version (use `tok version`): v0.0.12
- Drupal version: 7
- Operating system and version: OSX Sierra (v10.12.6) 

**Additional context**
![screen shot 2018-08-06 at 10 54 05 am](https://user-images.githubusercontent.com/1292616/43696465-705e408c-9981-11e8-8e33-df3c03c25ff2.png)

**Comment by otakumike** [comment]
Well that's silly. Thanks for the report Ben! 

FYI you can use `--force` to avoid the prompt. 

@yjimk FYI, looks like we might have busted something. I'll check it out and send up a PR tonight.

**Comment by otakumike** [comment]
This is fixed in the next release. Thanks again for reporting it Ben.
