### ISSUE TITLE
XDebug in Drush container

### ISSUE THREAD

**Issue by moroland** [ironstar-io/tokaido#88]
When developing Drush commands or tests (e.g. Behat), it would be very helpful to have the ability to use XDebug in the Drush container.

**Comment by otakumike** [comment]
We'll keep this card open and in the backlog. It would be good to implement this at some point, but it's low priority for now.

**Comment by otakumike** [comment]
I ended up building this as part of our 7.2 upgrade, so the admin container will now run xdebug on PHP 7.1 or 7.2. You can enable this with the new syntax: `tok config-set tokaido xdebug true` and then run `tok rebuild`.
