### ISSUE TITLE
Ability to check running status of all local tokaido instances

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#94]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem

**Describe the solution you'd like**
Would be nice to be able to check what active tok sites are currently running on local system. For example, I may have several tokaido projects on my local system. If I switch between projects, then I could have serveral instances of tokaido sites running at the same time. Would be good to be able to get an overview of which sites are active. I am thinking of something similar to `vagrant global-status`. 

By running something like `tok global-status` I can see list of all tokaido instances and their currently running state (e.g. running or stopped).

**Describe alternatives you've considered**
Not sure what alternatives there might be.

**Additional context**
n/a

**Comment by otakumike** [comment]
Great suggestion, and something @yjimk and I have discussed previously. I'll keep this ticket open but not sure when we'll be able to look into it. Thanks Ben!

**Comment by otakumike** [comment]
This is implemented now as `tok list` in the Tokaido 1.9 release candidate.
