### ISSUE TITLE
Drush container reports database as being ephemeral

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#95]
**What happened**:
When SSH into drush container the following message appears:
"... The Tokaido local development system is ephemeral. Each time you restart the
local Tokaido instance, your database is reset. Content not saved in the
/tokaido/site folder will also be lost forever. ..."

**What you expected to happen**:
My understanding is that the database is now persistent. If so the message should be updated to reflect this.

**How to reproduce it (as minimally and precisely as possible)**:
run tok up and then ssh into drush container.

**Anything else we need to know?**:
Screen shot of post drush container login message:
![screen shot 2018-12-14 at 5 55 23 pm](https://user-images.githubusercontent.com/1292616/49988168-ecbb3000-ffc9-11e8-84e2-ad63bf3b8452.png)

**Environment**:
- Tokaido version (use `tok version`): v1.4.2
- Drupal version: 8.x
- Operating system and version OSX Sierra v10.12.6

**Additional context**
N/A

**Comment by otakumike** [comment]
Thanks for pointing that out Ben! I'll fix it in the next release

**Comment by otakumike** [comment]
This is fixed in 1.5.0 coming out today. Thanks!
